spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/bloodbank
spring.datasource.username=blooduser
spring.datasource.password=bloodpass123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=BloodDonationSecretKey2024VeryLongAndSecure123456789
jwt.expiration=86400000

# FastAPI ML service URL
ml.service.url=http://localhost:8000

server.port=8080
